[mypy]
python_version = 3.10
mypy_path = src
explicit_package_bases = True
namespace_packages = True
exclude = (?x)(^\.venv/|^venv/|^build/|^dist/|^\.mypy_cache/)

[mypy-mazegenerator.*]
ignore_missing_imports = True

[mypy-pygame.*]
ignore_missing_imports = True

[mypy-PyInstaller.*]
ignore_missing_imports = True
